// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"google.golang.org/grpc"
	"grpc-mock/internal/stubs/echo"
)

// Injectors from wire.go:

func InitializeApp(server grpc.ServiceRegistrar, enableLogging bool) (*App, error) {
	echoServer := echo.NewEchoServer(server, enableLogging)
	app := &App{
		Echo: echoServer,
	}
	return app, nil
}

// wire.go:

type App struct {
	Echo *echo.EchoServer
}

var ProviderSet = wire.NewSet(echo.NewEchoServer, wire.Struct(new(App), "*"))
